services:
  web:
    build:
      context: ./client
      dockerfile: DockerfileClient
    ports:
      - "3000:3000"
    volumes:
     - ./client:/app
     - ./client/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
