services:
  web:
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - "0.0.0.0:5173:5173"  # Bind to all interfaces
    volumes:
     - .:/app
     - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0  # Allow external connections
    command: npm run dev -- --host 0.0.0.0
