version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    container_name: real-estate-server
    restart: unless-stopped
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
